name: Deploy Bot

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start Flask application
        run: |
          export FLASK_APP=app.py
          export FLASK_ENV=production
          gunicorn -b 0.0.0.0:5000 --workers 4 app:app
        # Make sure this step runs in the background or in a detached mode

      - name: Start Discord bot
        run: python bot.py
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        # Make sure this step also runs in the background or in a detached mode
