name: Deploy Bot

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Export secrets to environment variables
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}

      - name: Start Flask application
        run: |
          export FLASK_APP=app.py
          export FLASK_ENV=production
          gunicorn -b 0.0.0.0:5000 --workers 4 app:app &
        # Ensure this runs in the background or detached mode

      - name: Start Discord bot
        run: |
          python bot.py &
        # Ensure bot.py also fetches DISCORD_TOKEN and CHANNEL_ID from environment
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
